version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  ha_config:
  node-red_config:

services:
  pihole:
    build: ./pihole
    privileged: true
    restart: always
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    cap_add:
      - 'NET_ADMIN'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  # optional upstream resolver: https://github.com/jedisct1/dnscrypt-proxy
  # set pihole DNS1 and DNS2 service variables to 127.0.0.1:5300 to use this for upstream DNS
  # otherwise comment out this block to completely remove the service
  dnscrypt-proxy:
    build: ./dnscrypt-proxy
    ports:
      - '5300:53/tcp'
      - '5300:53/udp'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'


  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    network_mode: "host"
    privileged: true
    restart: always
    ports:
      - 0.0.0.0:8123:8123
    volumes:
      - 'ha_config:/config'
    depends_on:
      - mqtt

  mqtt:
      image: arm32v6/eclipse-mosquitto
      ports:
        - "1883:1883"

  nodered:
    image: nodered/node-red-docker:rpi-v8
    volumes:
      - 'node-red_config:/data'
    ports:
      - “1880:1880”
    user: 1000:1000
    restart: always